/*
Copyright 2019 The Pharmer Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	cloudv1 "github.com/pharmer/cloud/pkg/apis/cloud/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	testing "k8s.io/client-go/testing"
)

// FakeKubernetesVersions implements KubernetesVersionInterface
type FakeKubernetesVersions struct {
	Fake *FakeCloudV1
}

var kubernetesversionsResource = schema.GroupVersionResource{Group: "cloud.pharmer.io", Version: "v1", Resource: "kubernetesversions"}

var kubernetesversionsKind = schema.GroupVersionKind{Group: "cloud.pharmer.io", Version: "v1", Kind: "KubernetesVersion"}

// Get takes name of the kubernetesVersion, and returns the corresponding kubernetesVersion object, and an error if there is any.
func (c *FakeKubernetesVersions) Get(name string, options v1.GetOptions) (result *cloudv1.KubernetesVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(kubernetesversionsResource, name), &cloudv1.KubernetesVersion{})
	if obj == nil {
		return nil, err
	}
	return obj.(*cloudv1.KubernetesVersion), err
}

// List takes label and field selectors, and returns the list of KubernetesVersions that match those selectors.
func (c *FakeKubernetesVersions) List(opts v1.ListOptions) (result *cloudv1.KubernetesVersionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(kubernetesversionsResource, kubernetesversionsKind, opts), &cloudv1.KubernetesVersionList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &cloudv1.KubernetesVersionList{ListMeta: obj.(*cloudv1.KubernetesVersionList).ListMeta}
	for _, item := range obj.(*cloudv1.KubernetesVersionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Create takes the representation of a kubernetesVersion and creates it.  Returns the server's representation of the kubernetesVersion, and an error, if there is any.
func (c *FakeKubernetesVersions) Create(kubernetesVersion *cloudv1.KubernetesVersion) (result *cloudv1.KubernetesVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(kubernetesversionsResource, kubernetesVersion), &cloudv1.KubernetesVersion{})
	if obj == nil {
		return nil, err
	}
	return obj.(*cloudv1.KubernetesVersion), err
}

// Update takes the representation of a kubernetesVersion and updates it. Returns the server's representation of the kubernetesVersion, and an error, if there is any.
func (c *FakeKubernetesVersions) Update(kubernetesVersion *cloudv1.KubernetesVersion) (result *cloudv1.KubernetesVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(kubernetesversionsResource, kubernetesVersion), &cloudv1.KubernetesVersion{})
	if obj == nil {
		return nil, err
	}
	return obj.(*cloudv1.KubernetesVersion), err
}

// Delete takes name of the kubernetesVersion and deletes it. Returns an error if one occurs.
func (c *FakeKubernetesVersions) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(kubernetesversionsResource, name), &cloudv1.KubernetesVersion{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKubernetesVersions) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(kubernetesversionsResource, listOptions)

	_, err := c.Fake.Invokes(action, &cloudv1.KubernetesVersionList{})
	return err
}

// Patch applies the patch and returns the patched kubernetesVersion.
func (c *FakeKubernetesVersions) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *cloudv1.KubernetesVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(kubernetesversionsResource, name, pt, data, subresources...), &cloudv1.KubernetesVersion{})
	if obj == nil {
		return nil, err
	}
	return obj.(*cloudv1.KubernetesVersion), err
}
