/*
Copyright 2019 The Pharmer Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	testing "k8s.io/client-go/testing"
	cloudv1 "pharmer.dev/cloud/pkg/apis/cloud/v1"
)

// FakeCloudProviders implements CloudProviderInterface
type FakeCloudProviders struct {
	Fake *FakeCloudV1
}

var cloudprovidersResource = schema.GroupVersionResource{Group: "cloud.pharmer.io", Version: "v1", Resource: "cloudproviders"}

var cloudprovidersKind = schema.GroupVersionKind{Group: "cloud.pharmer.io", Version: "v1", Kind: "CloudProvider"}

// Get takes name of the cloudProvider, and returns the corresponding cloudProvider object, and an error if there is any.
func (c *FakeCloudProviders) Get(name string, options v1.GetOptions) (result *cloudv1.CloudProvider, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(cloudprovidersResource, name), &cloudv1.CloudProvider{})
	if obj == nil {
		return nil, err
	}
	return obj.(*cloudv1.CloudProvider), err
}

// List takes label and field selectors, and returns the list of CloudProviders that match those selectors.
func (c *FakeCloudProviders) List(opts v1.ListOptions) (result *cloudv1.CloudProviderList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(cloudprovidersResource, cloudprovidersKind, opts), &cloudv1.CloudProviderList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &cloudv1.CloudProviderList{ListMeta: obj.(*cloudv1.CloudProviderList).ListMeta}
	for _, item := range obj.(*cloudv1.CloudProviderList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Create takes the representation of a cloudProvider and creates it.  Returns the server's representation of the cloudProvider, and an error, if there is any.
func (c *FakeCloudProviders) Create(cloudProvider *cloudv1.CloudProvider) (result *cloudv1.CloudProvider, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(cloudprovidersResource, cloudProvider), &cloudv1.CloudProvider{})
	if obj == nil {
		return nil, err
	}
	return obj.(*cloudv1.CloudProvider), err
}

// Update takes the representation of a cloudProvider and updates it. Returns the server's representation of the cloudProvider, and an error, if there is any.
func (c *FakeCloudProviders) Update(cloudProvider *cloudv1.CloudProvider) (result *cloudv1.CloudProvider, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(cloudprovidersResource, cloudProvider), &cloudv1.CloudProvider{})
	if obj == nil {
		return nil, err
	}
	return obj.(*cloudv1.CloudProvider), err
}

// Delete takes name of the cloudProvider and deletes it. Returns an error if one occurs.
func (c *FakeCloudProviders) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(cloudprovidersResource, name), &cloudv1.CloudProvider{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCloudProviders) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(cloudprovidersResource, listOptions)

	_, err := c.Fake.Invokes(action, &cloudv1.CloudProviderList{})
	return err
}

// Patch applies the patch and returns the patched cloudProvider.
func (c *FakeCloudProviders) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *cloudv1.CloudProvider, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(cloudprovidersResource, name, pt, data, subresources...), &cloudv1.CloudProvider{})
	if obj == nil {
		return nil, err
	}
	return obj.(*cloudv1.CloudProvider), err
}
