/*
Copyright 2019 The Pharmer Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	testing "k8s.io/client-go/testing"
	cloudv1 "pharmer.dev/cloud/pkg/apis/cloud/v1"
)

// FakeCredentialFormats implements CredentialFormatInterface
type FakeCredentialFormats struct {
	Fake *FakeCloudV1
}

var credentialformatsResource = schema.GroupVersionResource{Group: "cloud.pharmer.io", Version: "v1", Resource: "credentialformats"}

var credentialformatsKind = schema.GroupVersionKind{Group: "cloud.pharmer.io", Version: "v1", Kind: "CredentialFormat"}

// Get takes name of the credentialFormat, and returns the corresponding credentialFormat object, and an error if there is any.
func (c *FakeCredentialFormats) Get(name string, options v1.GetOptions) (result *cloudv1.CredentialFormat, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(credentialformatsResource, name), &cloudv1.CredentialFormat{})
	if obj == nil {
		return nil, err
	}
	return obj.(*cloudv1.CredentialFormat), err
}

// List takes label and field selectors, and returns the list of CredentialFormats that match those selectors.
func (c *FakeCredentialFormats) List(opts v1.ListOptions) (result *cloudv1.CredentialFormatList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(credentialformatsResource, credentialformatsKind, opts), &cloudv1.CredentialFormatList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &cloudv1.CredentialFormatList{ListMeta: obj.(*cloudv1.CredentialFormatList).ListMeta}
	for _, item := range obj.(*cloudv1.CredentialFormatList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Create takes the representation of a credentialFormat and creates it.  Returns the server's representation of the credentialFormat, and an error, if there is any.
func (c *FakeCredentialFormats) Create(credentialFormat *cloudv1.CredentialFormat) (result *cloudv1.CredentialFormat, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(credentialformatsResource, credentialFormat), &cloudv1.CredentialFormat{})
	if obj == nil {
		return nil, err
	}
	return obj.(*cloudv1.CredentialFormat), err
}

// Update takes the representation of a credentialFormat and updates it. Returns the server's representation of the credentialFormat, and an error, if there is any.
func (c *FakeCredentialFormats) Update(credentialFormat *cloudv1.CredentialFormat) (result *cloudv1.CredentialFormat, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(credentialformatsResource, credentialFormat), &cloudv1.CredentialFormat{})
	if obj == nil {
		return nil, err
	}
	return obj.(*cloudv1.CredentialFormat), err
}

// Delete takes name of the credentialFormat and deletes it. Returns an error if one occurs.
func (c *FakeCredentialFormats) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(credentialformatsResource, name), &cloudv1.CredentialFormat{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCredentialFormats) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(credentialformatsResource, listOptions)

	_, err := c.Fake.Invokes(action, &cloudv1.CredentialFormatList{})
	return err
}

// Patch applies the patch and returns the patched credentialFormat.
func (c *FakeCredentialFormats) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *cloudv1.CredentialFormat, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(credentialformatsResource, name, pt, data, subresources...), &cloudv1.CredentialFormat{})
	if obj == nil {
		return nil, err
	}
	return obj.(*cloudv1.CredentialFormat), err
}
