/*
Copyright 2019 The Pharmer Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/pharmer/cloud/pkg/apis/cloud/v1"
	scheme "github.com/pharmer/cloud/pkg/client/clientset_generated/clientset/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	rest "k8s.io/client-go/rest"
)

// CredentialFormatsGetter has a method to return a CredentialFormatInterface.
// A group's client should implement this interface.
type CredentialFormatsGetter interface {
	CredentialFormats() CredentialFormatInterface
}

// CredentialFormatInterface has methods to work with CredentialFormat resources.
type CredentialFormatInterface interface {
	Create(*v1.CredentialFormat) (*v1.CredentialFormat, error)
	Update(*v1.CredentialFormat) (*v1.CredentialFormat, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.CredentialFormat, error)
	List(opts metav1.ListOptions) (*v1.CredentialFormatList, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.CredentialFormat, err error)
	CredentialFormatExpansion
}

// credentialFormats implements CredentialFormatInterface
type credentialFormats struct {
	client rest.Interface
}

// newCredentialFormats returns a CredentialFormats
func newCredentialFormats(c *CloudV1Client) *credentialFormats {
	return &credentialFormats{
		client: c.RESTClient(),
	}
}

// Get takes name of the credentialFormat, and returns the corresponding credentialFormat object, and an error if there is any.
func (c *credentialFormats) Get(name string, options metav1.GetOptions) (result *v1.CredentialFormat, err error) {
	result = &v1.CredentialFormat{}
	err = c.client.Get().
		Resource("credentialformats").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CredentialFormats that match those selectors.
func (c *credentialFormats) List(opts metav1.ListOptions) (result *v1.CredentialFormatList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.CredentialFormatList{}
	err = c.client.Get().
		Resource("credentialformats").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Create takes the representation of a credentialFormat and creates it.  Returns the server's representation of the credentialFormat, and an error, if there is any.
func (c *credentialFormats) Create(credentialFormat *v1.CredentialFormat) (result *v1.CredentialFormat, err error) {
	result = &v1.CredentialFormat{}
	err = c.client.Post().
		Resource("credentialformats").
		Body(credentialFormat).
		Do().
		Into(result)
	return
}

// Update takes the representation of a credentialFormat and updates it. Returns the server's representation of the credentialFormat, and an error, if there is any.
func (c *credentialFormats) Update(credentialFormat *v1.CredentialFormat) (result *v1.CredentialFormat, err error) {
	result = &v1.CredentialFormat{}
	err = c.client.Put().
		Resource("credentialformats").
		Name(credentialFormat.Name).
		Body(credentialFormat).
		Do().
		Into(result)
	return
}

// Delete takes name of the credentialFormat and deletes it. Returns an error if one occurs.
func (c *credentialFormats) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("credentialformats").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *credentialFormats) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("credentialformats").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched credentialFormat.
func (c *credentialFormats) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.CredentialFormat, err error) {
	result = &v1.CredentialFormat{}
	err = c.client.Patch(pt).
		Resource("credentialformats").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
