/*
Copyright 2019 The Pharmer Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	rest "k8s.io/client-go/rest"
	v1 "pharmer.dev/cloud/pkg/apis/cloud/v1"
	scheme "pharmer.dev/cloud/pkg/client/clientset/versioned/scheme"
)

// KubernetesVersionsGetter has a method to return a KubernetesVersionInterface.
// A group's client should implement this interface.
type KubernetesVersionsGetter interface {
	KubernetesVersions() KubernetesVersionInterface
}

// KubernetesVersionInterface has methods to work with KubernetesVersion resources.
type KubernetesVersionInterface interface {
	Create(*v1.KubernetesVersion) (*v1.KubernetesVersion, error)
	Update(*v1.KubernetesVersion) (*v1.KubernetesVersion, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.KubernetesVersion, error)
	List(opts metav1.ListOptions) (*v1.KubernetesVersionList, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.KubernetesVersion, err error)
	KubernetesVersionExpansion
}

// kubernetesVersions implements KubernetesVersionInterface
type kubernetesVersions struct {
	client rest.Interface
}

// newKubernetesVersions returns a KubernetesVersions
func newKubernetesVersions(c *CloudV1Client) *kubernetesVersions {
	return &kubernetesVersions{
		client: c.RESTClient(),
	}
}

// Get takes name of the kubernetesVersion, and returns the corresponding kubernetesVersion object, and an error if there is any.
func (c *kubernetesVersions) Get(name string, options metav1.GetOptions) (result *v1.KubernetesVersion, err error) {
	result = &v1.KubernetesVersion{}
	err = c.client.Get().
		Resource("kubernetesversions").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of KubernetesVersions that match those selectors.
func (c *kubernetesVersions) List(opts metav1.ListOptions) (result *v1.KubernetesVersionList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.KubernetesVersionList{}
	err = c.client.Get().
		Resource("kubernetesversions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Create takes the representation of a kubernetesVersion and creates it.  Returns the server's representation of the kubernetesVersion, and an error, if there is any.
func (c *kubernetesVersions) Create(kubernetesVersion *v1.KubernetesVersion) (result *v1.KubernetesVersion, err error) {
	result = &v1.KubernetesVersion{}
	err = c.client.Post().
		Resource("kubernetesversions").
		Body(kubernetesVersion).
		Do().
		Into(result)
	return
}

// Update takes the representation of a kubernetesVersion and updates it. Returns the server's representation of the kubernetesVersion, and an error, if there is any.
func (c *kubernetesVersions) Update(kubernetesVersion *v1.KubernetesVersion) (result *v1.KubernetesVersion, err error) {
	result = &v1.KubernetesVersion{}
	err = c.client.Put().
		Resource("kubernetesversions").
		Name(kubernetesVersion.Name).
		Body(kubernetesVersion).
		Do().
		Into(result)
	return
}

// Delete takes name of the kubernetesVersion and deletes it. Returns an error if one occurs.
func (c *kubernetesVersions) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("kubernetesversions").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *kubernetesVersions) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("kubernetesversions").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched kubernetesVersion.
func (c *kubernetesVersions) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.KubernetesVersion, err error) {
	result = &v1.KubernetesVersion{}
	err = c.client.Patch(pt).
		Resource("kubernetesversions").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
